-- Add ideal_client_profile columns to user_profiles table
-- This allows storing comprehensive ideal client profiles from the Ideal Client Extractor tool

ALTER TABLE user_profiles
ADD COLUMN IF NOT EXISTS ideal_client_profile TEXT,
ADD COLUMN IF NOT EXISTS ideal_client_profile_updated_at TIMESTAMP WITH TIME ZONE;

-- Add comments for documentation
COMMENT ON COLUMN user_profiles.ideal_client_profile IS 'Comprehensive ideal client profile generated by the Ideal Client Extractor tool';
COMMENT ON COLUMN user_profiles.ideal_client_profile_updated_at IS 'Timestamp when the ideal client profile was last updated'; 