-- Add psychographic_brief columns to user_profiles table
-- This allows storing comprehensive psychographic briefs from the Ideal Client Extractor tool

ALTER TABLE user_profiles 
ADD COLUMN IF NOT EXISTS psychographic_brief TEXT,
ADD COLUMN IF NOT EXISTS psychographic_brief_updated_at TIMESTAMP WITH TIME ZONE;

-- Add a comment to document the purpose
COMMENT ON COLUMN user_profiles.psychographic_brief IS 'Comprehensive psychographic brief generated by the Ideal Client Extractor tool';
COMMENT ON COLUMN user_profiles.psychographic_brief_updated_at IS 'Timestamp when the psychographic brief was last updated'; 